development:
  adapter: mysql2
  database: igarsharding_development
  username: root
  pool: 20
  timeout: 5000

test:
  adapter: mysql2
  database: igarsharding_test
  username: root
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: igarsharding_production
  username: root
  pool: 5
  timeout: 5000
