default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: db
  username: root
  password:
  port: 3306

development:
  <<: *default
  database: octopussy_development

test:
  <<: *default
  database: octopussy_test

production:
  <<: *default
  database: octopussy_production
