development:
  adapter: mysql2
  database: shard_demo
  username: root
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  database: octopussy_test
  username: root
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: octopussy_production
  username: root
  pool: 5
  timeout: 5000
